deploy_production:
  stage: deploy
  environment: Production
  tags:
    - prod
  only:
    - master
  script:
    - cd /tmp
    - git clone https://github.com/petbccufscar/sitepetbcc
    - rsync -r sitepetbcc/ ~/sitepetbcc
    - cd ~/sitepetbcc
    - backup_db
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py collectstatic
    - rsync -r static/* /var/www/static/
    - sudo systemctl restart gunicorn
    
